image: quickcorp/qcobjects:latest

pages:
  stage: deploy
  script:
  - mkdir public
  - cp -Rf css/ public/
  - cp -Rf img/ public/
  - cp -Rf js/ public/
  - cp -Rf spec/ public/
  - cp -Rf templates/ public/
  - cp *.* public/
  - cd public
  - npm i
  - npm i -D eslint-config-qcobjects
  - npm test
  artifacts:
    paths:
    - public
  only:
  - main
